const { User, Post, Reaction } = require('../models');
require('dotenv').config();

/**
 * @function getAllReactions  Get all reactions from the database and return them to the user.
 *
 * @param {object} _req - The request object
 * @param {object} res - The response object
 *
 * @returns {object} - response
 */
exports.getAllReactions = async (_req, res) => {
  try {
    const findAllReactions = await Reaction.findAll({
      order: [
        ['createdAt', 'DESC'],
      ],
    });
    if (findAllReactions) {
      return res.status(200).json(findAllReactions);
    }
  } catch (error) {
    return res.status(500).json({ message: 'Cannot get Reactions. Please try again' });
  }
  return true;
};

/**
 * @function createReaction The function create a reaction, but before that,
 * the function will check if the post where the reaction is related exists,
 * if not, it will return a 404 error. After that, it will check the format of the data,
 * and if it's good, it will check if the reaction don't already exists, if not,
 * it will create a new reaction
 *
 * @param {object} req - The request object
 * @param {object} req.body - The request body
 * @param {object} req.token - The token generated by connecting
 * @param {object} req.token.UserId - The UserId in the token
 * @param {number} req.body.type - The type of reaction
 * @param {object} req.body.PostId - The ID of the post
 * @param {object} res - The response object
 *
 * @returns {object} - response
 */
exports.createReaction = async (req, res) => {
  const postSearch = await Post.findOne({ where: { id: req.body.PostId } });
  if (!postSearch) {
    return res.status(404).json({ message: 'Post Not Found' });
  }
  const { PostId, type } = req.body;
  if (typeof type !== 'number' || Number.isNaN(type)) {
    return res.status(400).json({ message: 'Type must be a number' });
  }
  if (typeof PostId !== 'number' || Number.isNaN(PostId)) {
    return res.status(400).json({ message: 'PostId must be a number' });
  }
  try {
    const searchReaction = await Reaction.findOne({
      where: {
        PostId, UserId: req.token.UserId,
      },
    });
    if (searchReaction) {
      return res.status(409).json({ message: 'Reaction already exists' });
    }
    const reactionCreation = await Reaction.create({
      type,
      PostId,
      UserId: req.token.UserId,
    });
    if (reactionCreation) {
      return res.status(201).json({ message: 'Reaction Created' });
    }
  } catch (error) {
    return res.status(500).json({ message: 'Something went wrong. Please try again.' });
  }
  return true;
};

/**
 * @function getOneReaction Find a reaction by its ID
 *
 * @param {object} req - The request object
 * @param {object} req.params - The params in the URL
 * @param {number} req.params.ReactionId - The ID of the reaction in the URL
 * @param {object} res - The response object
 *
 * @returns {object} - response
 */
exports.getOneReaction = async (req, res) => {
  try {
    const findOneReaction = await Reaction.findOne({
      where: {
        id: req.params.ReactionId,
      },
      include: [{
        model: Post,
        attributes: ['title', 'content'],
      },
      {
        model: User,
        attributes: ['username', 'avatar'],
      }],
    });
    if (findOneReaction) {
      return res.status(200).json(findOneReaction);
    }
    return res.status(404).json({ message: 'Reaction not found' });
  } catch (error) {
    return res.status(500).json({ message: 'Cannot get this reaction. Please try again.' });
  }
};

/**
 * @function modifyReaction The modifyReaction function is used to modify a reaction,
 * the function checks if the reaction exists, or returns a 404 error.
 * It checks if the format of the data is correct or returns a 400 error if not.
 *
 * @param {object} req - The request object
 * @param {object} req.token - The token generated by connecting
 * @param {number} req.token.UserId - The ID of the user in the token
 * @param {object} req.params - The params in the URL
 * @param {number} req.params.ReactionId - The ID of the reaction in the URL
 * @param {object} req.body - The request body
 * @param {number} req.body.type - The type of reaction
 * @param {object} req.body.PostId - The ID of the post
 * @param {object} res - The response object
 *
 * @returns {object} - response
 */
exports.modifyReaction = async (req, res) => {
  const reactionFind = await Reaction.findOne({ where: { id: req.params.ReactionId } });
  if (!reactionFind) {
    return res.status(404).json({ message: 'Reaction not found' });
  }
  const searchPost = await Post.findOne({ where: { id: req.body.PostId } });
  if (!searchPost) {
    return res.status(404).json({ message: 'Post not found' });
  }
  const { PostId, type } = req.body;
  if (typeof type !== 'number' || Number.isNaN(type)) {
    return res.status(400).json({ message: 'Type must be a number' });
  }
  if (typeof PostId !== 'number' || Number.isNaN(PostId)) {
    return res.status(400).json({ message: 'PostId must be a number' });
  }
  try {
    const searchReaction = await Reaction.findOne({
      where: {
        PostId, UserId: req.token.UserId, type,
      },
    });
    if (searchReaction) {
      return res.status(409).json({ message: 'Reaction already exists' });
    }
    let reactionObject = {};
    reactionObject = { ...req.body };
    const updateReaction = await Reaction.update({
      ...reactionObject,
    }, { where: { id: req.params.ReactionId } });
    if (updateReaction) {
      return res.status(200).json({ message: 'Reaction successfully updated' });
    }
  } catch (error) {
    return res.status(400).json({ message: 'Something went wrong. Please try again.' });
  }
  return true;
};

/**
 * @function deleteReaction Find the reaction with the given ID,
 * if it exists, delete it and return a success message.
 *
 * @param {object} req - The request object
 * @param {object} req.params - The params in the URL
 * @param {number} req.params.ReactionId - The ID of the reaction in the URL
 * @param {object} res - The response object
 *
 * @returns {object} - response
 */
exports.deleteReaction = async (req, res) => {
  try {
    const reactionFind = await Reaction.findOne({ where: { id: req.params.ReactionId } });
    if (!reactionFind) {
      return res.status(404).json({ message: 'Reaction not found' });
    }
    const deleteReaction = await Reaction.destroy({ where: { id: req.params.ReactionId } });
    if (deleteReaction) {
      return res.status(200).json({ message: 'Reaction has been deleted' });
    }
    return true;
  } catch (error) {
    return res.status(500).json({ message: 'Something went wrong. Please try again.' });
  }
};
